import { FACTION_ALL } from "scripts_bType/FACTION_NAMES.ts";
import { OUTPUT_DecrementGlobal } from "scripts_bType/output/OUTPUT_DecrementGlobal.ts";
import { FORESIGHT } from "scripts_bType/utility/Foresight.ts";
import { VILLAGE_SIZE_ALL } from "scripts_bType/village/VILLAGE_SizeHierarchy.ts";

import { FACTION_EntryUnified } from "./FACTION_EntryUnified.ts";
import { FACTION_GetShortName } from "./FACTION_GetShortName.ts";
import { FACTION_GetType } from "./FACTION_GetType.ts";

/**
 * Registry managing faction establishment tracking systems through global variables and procedural methods.
 * @readonly
 * @remarks
 * Contains generators for faction-specific global variable names (gvCentralBaseId, gvSizeCount, gvDayEstablished, gvPreGameRemaining) and
 * validation methods (IsEstablished, IsCentralBaseEstablished, GetNextBaseSizeToBuild).
 * Maintains pre-game preparation counters (SetPreGameRemaining/DecrementPreGameRemaining) and
 * base construction quotas (SetSizeCount/GetSizeCount/DecrementSizeCount).
 * Reserved sections for mob alliance factions (creeper/skeleton/zombie) indicate planned expansions for occupation systems.
 * GetFactions method enables establishment state filtering across FACTION_ALL registry.
 * All methods operate without list structures, using direct variable access and procedural validation.
 */
export const FACTION_Establishment = {
  /**
   * Central base identifier generator for faction establishment tracking.
   * @param factionName Target faction identifier.
   * @returns {string} Formatted global variable name.
   * @remarks
   * Constructs "gv_{factionType}_{factionShortName}_central_base" identifiers using FACTION_GetType and FACTION_GetShortName.
   * Used for persistent storage of central base entity IDs during world generation.
   */
  gvCentralBaseId: function (factionName: FactionNameId): string {
    const factionShortName = FACTION_GetShortName(factionName);
    const factionType = FACTION_GetType(factionName);
    return `gv_${factionType}_${factionShortName}_central_base`;
  },

  /**
   * Size-specific base count variable name generator.
   * @param factionName Target faction identifier.
   * @param size Village scale classification.
   * @returns {string} Formatted global variable name.
   * @remarks
   * Creates "gv_faction_{factionType}_{factionShortName}_size_count_{size}" identifiers for tracking base construction progress.
   * Used in procedural generation quota systems and faction progression validation.
   */
  gvSizeCount: function (
    factionName: FactionNameId,
    size: VillageSizeKey,
  ): string {
    const factionShortName = FACTION_GetShortName(factionName);
    const factionType = FACTION_GetType(factionName);
    return `gv_faction_${factionType}_${factionShortName}_size_count_${size}`;
  },

  /**
   * Establishment day tracker variable name generator.
   * @param factionName Target faction identifier.
   * @returns {string} Formatted global variable name.
   * @remarks
   * Produces "gv_faction_{factionType}_{factionShortName}_day_established" identifiers for temporal analytics.
   * Persists through game sessions to track faction establishment timelines.
   */
  gvDayEstablished: function (factionName: FactionNameId): string {
    const factionShortName = FACTION_GetShortName(factionName);
    const factionType = FACTION_GetType(factionName);
    return `gv_faction_${factionType}_${factionShortName}_day_established`;
  },

  /**
   * Pre-game preparation counter variable name generator.
   * @param factionName Target faction identifier.
   * @returns {string} Formatted global variable name.
   * @remarks
   * Generates "gv_faction_{factionType}_{factionShortName}_pregame_remaining" identifiers for initialization tracking.
   * Used during world setup phase for faction readiness validation.
   */
  gvPreGameRemaining: function (factionName: FactionNameId): string {
    const factionShortName = FACTION_GetShortName(factionName);
    const factionType = FACTION_GetType(factionName);
    return `gv_faction_${factionType}_${factionShortName}_pregame_remaining`;
  },

  /**
   * Sets faction base size construction quota.
   * @param factionName Target faction identifier.
   * @param size Village scale classification.
   * @param count Target construction quantity.
   * @returns {NoReturn}
   * @remarks
   * Updates global variables generated by gvSizeCount with specified counts.
   * Critical for procedural generation systems and faction progression pacing.
   */
  SetSizeCount: function (
    factionName: FactionNameId,
    size: VillageSizeKey,
    count: number,
  ): void {
    OUTPUT_SetGlobalVariable(this.gvSizeCount(factionName, size), count);
  },

  /**
   * Retrieves faction base size construction quota.
   * @param factionName Target faction identifier.
   * @param size Village scale classification.
   * @returns {number} Current construction count value.
   * @remarks
   * Queries global variables generated by gvSizeCount.
   * Returns 0 if variable is uninitialized or faction is invalid.
   */
  GetSizeCount: function (
    factionName: FactionNameId,
    size: VillageSizeKey,
  ): number {
    return QUERY_GetGlobalVariable(this.gvSizeCount(factionName, size));
  },

  /**
   * Decrements faction base size construction quota with establishment validation.
   * @param factionName Target faction identifier.
   * @param size Village scale classification.
   * @returns {boolean | number | undefined} Updated count or false if invalid.
   * @remarks
   * Checks FACTION_EntryUnified.IsAllowed before modification.
   * Prevents decrementation for established factions with error logging.
   * Returns undefined when faction entry validation fails.
   */
  DecrementSizeCount: function (
    factionName: FactionNameId,
    size: VillageSizeKey,
  ): boolean | number | undefined {
    if (!FACTION_EntryUnified.IsAllowed(factionName)) {
      // If faction isn't allowed (i.e. not in FACTION_ALL) then we consider it not established.
      return false;
    }
    if (this.IsEstablished(factionName)) {
      FORESIGHT.error(
        `Decrementing size count for faction ${factionName} which is already established. Check your logic.`,
      );
      return;
    }
    OUTPUT_DecrementGlobal(this.gvSizeCount(factionName, size));
    return this.GetSizeCount(factionName, size);
  },

  /**
   * Checks complete faction establishment status.
   * @param factionName Target faction identifier.
   * @returns {boolean} True if all size quotas are fulfilled.
   * @remarks
   * Validates FACTION_EntryUnified.IsEntered status first.
   * Uses VILLAGE_SIZE_ALL to verify all size counts are zero.
   * Returns false for uninitialized factions or incomplete construction progress.
   */
  IsEstablished: function (factionName: FactionNameId): boolean {
    // If the faction hasn't "entered" yet, it cannot be established.
    if (!FACTION_EntryUnified.IsEntered(factionName)) {
      return false;
    }

    // Dynamically check if all sizes have zero remaining count.
    return VILLAGE_SIZE_ALL.every((villageSize: VillageSizeKey) => {
      const remainingCount = this.GetSizeCount(factionName, villageSize);
      return remainingCount === 0;
    });
  },

  /**
   * Checks central base establishment status.
   * @param faction Target faction identifier.
   * @returns {boolean} True if central base ID is registered.
   * @remarks
   * Queries global variable generated by gvCentralBaseId.
   * Returns false when no central base has been constructed/registered.
   */
  IsCentralBaseEstablished: function (faction: FactionNameId): boolean {
    return QUERY_GetGlobalVariable(this.gvCentralBaseId(faction)) > 0;
  },

  /**
   * Retrieves central base identifier for specified factions.
   * @param faction Target faction identifier.
   * @returns {number} Stored central base entity ID or 0 if unregistered.
   * @remarks
   * Accesses global variables generated by gvCentralBaseId.
   * Returns 0 when central base construction is incomplete or untracked.
   */
  GetCentralBaseID: function (faction: FactionNameId): number {
    return QUERY_GetGlobalVariable(this.gvCentralBaseId(faction));
  },

  /**
   * Retrieves pre-game preparation counter value.
   * @param faction Target faction identifier.
   * @param vID Village ID
   * @returns {number} Remaining pre-game steps or 0 if unregistered.
   * @remarks
   * Queries global variables generated by gvPreGameRemaining.
   * Used during world initialization for faction activation sequencing.
   */
  SetCentralBaseID: function (faction: FactionNameId, vID: VillageID): void {
    OUTPUT_SetGlobalVariable(this.gvCentralBaseId(faction), vID);
  },

  /**
   * Retrieves pre-game preparation counter value.
   * @param faction Target faction identifier.
   * @returns {number} Remaining pre-game steps or 0 if unregistered.
   * @remarks
   * Queries global variables generated by gvPreGameRemaining.
   * Used during world initialization for faction activation sequencing.
   */
  GetPreGameRemaining: function (faction: FactionNameId): number {
    return QUERY_GetGlobalVariable(this.gvPreGameRemaining(faction));
  },

  /**
   * Initializes pre-game preparation counters.
   * @param faction Target faction identifier.
   * @param preGameAmount Initial counter value.
   * @returns {NoReturn}
   * @remarks
   * Sets global variables via gvPreGameRemaining with specified values.
   * Used for controlling faction entry timing during world generation.
   */
  SetPreGameRemaining: function (
    faction: FactionNameId,
    preGameAmount: number,
  ): void {
    OUTPUT_SetGlobalVariable(this.gvPreGameRemaining(faction), preGameAmount);
  },

  /**
   * Decrements pre-game preparation counter.
   * @param faction Target faction identifier.
   * @returns {NoReturn}
   * @remarks
   * Uses OUTPUT_DecrementGlobal on gvPreGameRemaining variables.
   * Triggers faction entry systems when counter reaches zero.
   */
  DecrementPreGameRemaining: function (faction: FactionNameId): void {
    OUTPUT_DecrementGlobal(this.gvPreGameRemaining(faction));
  },

  /**
   * Retrieves factions based on establishment status.
   * @param established Target establishment state (true/false).
   * @returns {FactionNameId[]} Array of factions matching criteria.
   * @remarks
   * Iterates FACTION_ALL registry and filters using IsEstablished validation.
   * Returns empty array when no factions match the specified state.
   */
  GetFactions: function (established: boolean): FactionNameId[] {
    const factions: FactionNameId[] = [];
    for (const faction of FACTION_ALL) {
      if (this.IsEstablished(faction) === established) {
        factions.push(faction);
      }
    }
    return factions;
  },

  /**
   * Determines next required base size for faction construction.
   * @param faction Target faction identifier.
   * @returns {VillageSizeKey | null} Next size to build or null if complete.
   * @remarks
   * Iterates VILLAGE_SIZE_ALL to find first size with positive remaining count.
   * Returns null when faction is fully established or has invalid configuration.
   */
  GetNextBaseSizeToBuild: function (
    faction: FactionNameId,
  ): VillageSizeKey | null {
    // Iterate through all sizes in VILLAGE_SizeAll
    for (const villageSize of VILLAGE_SIZE_ALL) {
      const remainingCount = this.GetSizeCount(faction, villageSize);
      if (remainingCount > 0) {
        return villageSize; // Return the first size with a remaining count greater than 0
      }
    }
    return null; // If no size has a remaining count greater than 0, return null
  },
};
