/*
========== INFO ==========
This file is composed manually. 
These functions are managed on the code end, contact the BSharp programmer team if this file is out of date.
These functions are "special" and will not be generated by the doc generator. BSharp programmers would usually add them manually
==========================
*/

/**
 * Logic to perform when the server begins.
 * No listener required. All bootstrap snippets will fire at the beginning of a new game.
 * @param snippetName
 * @param callback
 */
declare function SNIPPET_Bootstrap(
  snippetName: string,
  callback: BootstrapCallback,
): void;
declare type BootstrapCallback = () => void;

/**
 * Current patch version is: 1
 * Logic to perform when processing a patch.
 * No listener required. All bootstrap snippets will fire at the beginning of a new game.
 * This snippet runs at the start of EVERY game, even after save-load.
 * @param snippetName
 * @param minPatchVersion
 * @param callback
 */
declare function SNIPPET_ProcessPatch(
  snippetName: string,
  minPatchVersion: number,
  callback: ProcessPatchBootstrapCallback,
): void;
declare type ProcessPatchBootstrapCallback = (newVersion: number) => void;

/**
 * Logic to perform when the server begins.
 * No listener required. All bootstrap snippets will fire at the beginning of a new game.
 * This snippet runs at the start of EVERY game, even after save-load.
 * @param snippetName
 * @param callback
 */
declare function SNIPPET_GameLoadBootstrap(
  snippetName: string,
  callback: GameLoadBootstrapCallback,
): void;
declare type GameLoadBootstrapCallback = (isSaveLoaded: boolean) => void;

/**
 * Similar to Bootstrap. The name of the snippet should match the rule that is being reacted to.
 * Passes along the value of the rule as a parameter.
 * No listener required. All rule initialized snippets will fire at the beginning of a new game.
 * @param snippetName
 * @param callback
 */
declare function SNIPPET_RuleInitialized(
  snippetName: string,
  callback: RuleInitializedCallback,
): void;
declare type RuleInitializedCallback = (ruleValue: VariantData) => void;

/**
 * Similar to Bootstrap. The name of the snippet should match the game mode this is being reacted to.
 * No listener required. All rule initialized snippets will fire at the beginning of a new game.
 * @param snippetName
 * @param callback
 */
declare function SNIPPET_InheritsFromGameMode(
  snippetName: string,
  callback: InheritsFromGameModeCallback,
): void;
declare type InheritsFromGameModeCallback = () => void;

/**
 * Registers a callback for when a game setting is initialized
 * @param settingName The name of the game setting to monitor
 * @param callback Handler to execute when the setting is initialized
 */
declare function SNIPPET_GameSettingInitialized(
  settingName: string,
  callback: GameSettingCallback,
): void;

/**
 * Callback type for game setting initialization handlers
 * Receives the setting value container object
 */
declare type GameSettingCallback = (value: {
  /** The actual value of the game setting */
  value: number | boolean | string;
}) => void;

/**
 * Registers a callback for game launch events from the lobby.
 * Differentiates between first launch and subsequent launches.
 * @param {string} snippetName Unique identifier
 * @param {LaunchFromLobbyCallback} callback Event handler
 * @example
 * SNIPPET_LaunchFromLobby("main_menu_init", (firstLaunch) => {
 *   if(firstLaunch) SHOW_Tutorial();
 *   else LOAD_SaveGame();
 * });
 * @description
 * Use cases:
 * - Initial setup routines
 * - Save game management
 * - Version migration logic
 */
declare function SNIPPET_LaunchFromLobby(
  snippetName: string,
  callback: LaunchFromLobbyCallback,
): void;

/**
 * Callback signature for lobby launch events.
 * Provides launch context information.
 * @param {boolean} firstLaunch True if first game launch
 */
declare type LaunchFromLobbyCallback = (firstLaunch: boolean) => void;
