import fs from "fs";
import path from "path";

const BLOCK_IDENTIFIER_TYPE_PATH = path.join(
  __dirname,
  "../../generated/blocks/enums/BlockIdentifierType.d.ts",
);

/**
 * Comprehensive block registry with automatic type updates and validation.
 * Maintains synchronization between runtime instances and TypeScript types.
 * @class BlockRegistry
 */
class BlockRegistry {
  private static instance: BlockRegistry;
  private blocks: Map<string, BlockSchema[]> = new Map();
  private registeredIdentifiers: Set<string> = new Set();
  private cache: Map<string, BlockSchema> = new Map();
  private versionHistory: Map<string, string[]> = new Map();

  /**
   *
   */
  private constructor() {
    this.initializeTypeFile();
    this.loadExistingIdentifiers();
  }

  /**
   * @returns {BlockRegistry}
   */
  public static getInstance(): BlockRegistry {
    if (!BlockRegistry.instance) {
      BlockRegistry.instance = new BlockRegistry();
    }
    return BlockRegistry.instance;
  }

  /**
   *
   */
  private initializeTypeFile(): void {
    if (!fs.existsSync(BLOCK_IDENTIFIER_TYPE_PATH)) {
      fs.writeFileSync(
        BLOCK_IDENTIFIER_TYPE_PATH,
        "// Auto-generated block types\n",
      );
    }
  }

  /**
   * Loads existing block identifiers from the type file
   */
  private loadExistingIdentifiers(): void {
    if (!fs.existsSync(BLOCK_IDENTIFIER_TYPE_PATH)) {
      return;
    }
    const fileContent = fs.readFileSync(BLOCK_IDENTIFIER_TYPE_PATH, "utf-8");
    const identifierRegex = /'([a-z0-9_]+:[a-z0-9_]+)'/g;
    let match;
    while ((match = identifierRegex.exec(fileContent)) !== null) {
      this.registeredIdentifiers.add(match[1]);
    }
  }

  /**
   * Registers a new block and updates type definitions
   * @param identifier
   * @param block
   */
  public addBlock(identifier: string, block: BlockSchema): void {
    const version = block.metadata?.schemaVersion ?? "1.0.0"; // Use nullish coalescing operator

    if (this.blocks.has(identifier)) {
      const versions = this.blocks.get(identifier)!;
      if (
        versions.some((b: BlockSchema) => b.metadata?.schemaVersion === version)
      ) {
        throw new Error(
          `Block ${identifier} version ${version} already exists`,
        );
      }
    } else {
      this.blocks.set(identifier, []);
      this.versionHistory.set(identifier, []);
    }

    this.validateIdentifier(identifier);

    const versions = this.blocks.get(identifier)!;
    versions.push(block);
    this.versionHistory.get(identifier)!.push(version);

    this.cache.set(identifier, block);
    this.registeredIdentifiers.add(identifier);

    this.updateTypeDefinitions();
  }

  /**
   * Retrieves a block with type-safe return value
   * @param identifier
   * @param version
   * @returns {BlockSchema}
   */
  public getBlock(identifier: string, version?: string): BlockSchema {
    if (this.cache.has(identifier)) {
      return this.cache.get(identifier)!;
    }

    const versions = this.blocks.get(identifier);
    if (!versions) {
      throw new Error(`Block ${identifier} not found in registry`);
    }

    if (version) {
      const block = versions.find(
        (b: BlockSchema) => b.metadata?.schemaVersion === version,
      );
      if (!block) {
        throw new Error(`Version ${version} not found for ${identifier}`);
      }
      return block;
    }

    const latestBlock = versions[versions.length - 1];
    this.cache.set(identifier, latestBlock);
    return latestBlock;
  }

  /**
   * Checks block existence with type narrowing support
   * @param identifier
   * @returns {boolean}
   */
  public hasBlock(identifier: string): boolean {
    return this.blocks.has(identifier);
  }

  /**
   * Generates updated type definitions file
   */
  private updateTypeDefinitions(): void {
    const typeContent = this.generateTypeContent();
    fs.writeFileSync(BLOCK_IDENTIFIER_TYPE_PATH, typeContent);
  }

  /**
   * Creates type definition content with current registry state
   * @returns {string}
   */
  private generateTypeContent(): string {
    const identifiers = Array.from(this.registeredIdentifiers)
      .map((id) => `  | '${id}'`)
      .join("\n");
    return `// Auto-generated by BlockRegistry - DO NOT EDIT MANUALLY
declare type BlockIdentifierType =\n${identifiers};\n`;
  }

  /**
   * @returns {string}
   */
  private generateVersionedTypeContent(): string {
    let content = "declare type VersionedBlockIdentifier =\n";
    this.blocks.forEach((versions, id) => {
      versions.forEach((block) => {
        const version = block.metadata?.schemaVersion ?? "1.0.0"; // Use nullish coalescing operator
        content += `  | { id: '${id}', version: '${version}' }\n`;
      });
    });
    return content + ";\n";
  }

  /**
   * Validates block identifier format
   * @param identifier
   */
  private validateIdentifier(identifier: string): void {
    const FORMAT_REGEX = /^[a-z0-9_]+:[a-z0-9_]+$/;
    const MAX_LENGTH = 100;

    if (!FORMAT_REGEX.test(identifier)) {
      throw new Error(
        `Invalid block identifier format: ${identifier}. Must follow namespace:name pattern using lowercase letters, numbers, and underscores.`,
      );
    }

    if (identifier.length > MAX_LENGTH) {
      throw new Error(
        `Block identifier exceeds ${MAX_LENGTH} characters: ${identifier}`,
      );
    }

    const [namespace] = identifier.split(":");
    if (namespace === "minecraft") {
      throw new Error(
        `Reserved namespace 'minecraft' cannot be used for custom blocks`,
      );
    }
  }

  /**
   * Returns all registered identifiers with proper typing
   * @returns {string}
   */
  public getRegisteredIdentifiers(): string[] {
    return Array.from(this.registeredIdentifiers);
  }

  /**
   * Clears registry and type definitions (development use only)
   */
  public clearRegistry(): void {
    this.blocks.clear();
    this.registeredIdentifiers.clear();
    this.cache.clear();
    this.versionHistory.clear();
    fs.writeFileSync(BLOCK_IDENTIFIER_TYPE_PATH, "");
  }

  /**
   * Updates an existing block in the registry
   * @param identifier
   * @param block
   */
  public updateBlock(identifier: string, block: BlockSchema): void {
    if (!this.blocks.has(identifier)) {
      throw new Error(`Block ${identifier} not found in registry`);
    }

    const versions = this.blocks.get(identifier)!;
    const version = block.metadata?.schemaVersion ?? "1.0.0"; // Use nullish coalescing operator

    // Replace the block with the same version or add as a new version
    const index = versions.findIndex(
      (b: BlockSchema) => b.metadata?.schemaVersion === version,
    );
    if (index !== -1) {
      versions[index] = block;
    } else {
      versions.push(block);
      this.versionHistory.get(identifier)!.push(version);
    }

    this.cache.set(identifier, block);
    this.updateTypeDefinitions();
  }
}

/** */
export const blockRegistry = BlockRegistry.getInstance();
