import { OWNER_VILLAGE_OPT_OUT } from "scripts_bType/consts/OWNER_VILLAGE_OPT_OUT.ts";

/**
 * Listens for villages generated by specific factions.
 * Useful for procedural content tracking.
 * @param {string} snippet Listener identifier
 * @param {string} factionName Generating faction
 * @param {number} [ownerVillageId=OWNER_VILLAGE_OPT_OUT] Owning village
 * @example
 * // Track cultist outposts
 * LF_VillageGeneratedForFaction("cult_spawn", "cultists");
 *
 * LISTENFOR_VillageGenerated({
 *   snippet: "cult_spawn",
 *   callback: (villageId) => {
 *     SPAWN_Enemies(villageId, "cultist", 5);
 *   }
 * });
 * @description
 * Generation types:
 * - Procedural world gen
 * - Scripted spawns
 * - Dynamic difficulty placement
 *
 * Use for:
 * - Populating new areas
 * - Balancing encounters
 * - Tracking faction expansion
 */
export const LF_VillageGeneratedForFaction = (
  snippet: string,
  factionName: FactionNameId,
  ownerVillageId = OWNER_VILLAGE_OPT_OUT,
): void => {
  LISTENFOR_VillageGenerated({
    snippet: snippet,
    ownerVillageId: ownerVillageId,
    factionName: factionName,
  });
};
